### PR TITLE
DDD-3 Incremental snapshotting

### PR DESCRIPTION
**Pull request by jpechane**
Alternative names proposed - phased, rolling, travelling, progressive

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, can you send a mail to the list, so to share this proposal, as we discussed? Thx!

**Comment by gunnarmorling** [comment]
@jpechane, pushed a commit with a few cosmetic changes. Will merge it, so people can read the rendered version (including images), so to facilitate the discussion. Thx a lot!

**Comment by kgalieva** [comment]
@jpechane @gunnarmorling  where can I find the discussion?

**Comment by gunnarmorling** [comment]
Hey @kgalieva, we'll start a discussion on the [mailing list](https://groups.google.com/g/debezium) next week. Your input and feedback will be very welcomed!

**Comment by jpechane** [comment]
@kgalieva Please see https://groups.google.com/g/debezium/c/JS3LjfE3WQo

**Pull request merged**
